### ISSUE TITLE
Help with building MAXENT model on HPC

### ISSUE THREAD

**Issue by WeiyeHuang** [biomodhub/biomod2#424]
**Context and question**
When using the MAXENT algorithm to build models on a SLURM cluster, the algorithm fails with the error message "Exception in thread java.awt.AWTError: Can't connect to X11 window server using 'localhost:17.0' as the value of the DISPLAY variable." Meanwhile, the `MAXNET` algorithm works without any issues.

**Code used**
```R
# Formating data
formatted_data <- BIOMOD_FormatingData(
  resp.name = "keteleeria",
  resp.var = train_data,
  expl.var = modern_clim,
  eval.resp.var = test_data,
  eval.expl.var = modern_clim,
  dir.name = "./Models"
)
formatted_data

# Set the parameters for model training to the default parameters
model_list <- c("GLM", "GBM", "CTA", "MARS", "RF", "XGBOOST", "MAXNET", "MAXENT")
modeling_option <- bm_ModelingOptions(data.type = "binary",
                                      models = model_list,
                                      strategy = "bigboss",
                                      user.base = "bigboss",
                                      bm.format = formatted_data)
evaluation_list <- c("ROC", "TSS", "ACCURACY", "POD")

# Train models
modeval_for_evaluation <- BIOMOD_Modeling(
  bm.format = formatted_data,
  modeling.id = as.character(format(Sys.time(), "%s")),    
  models = model_list,
  bm.options = modeling_option,
  CV.nb.rep = 16,
  CV.perc = 0.7,
  CV.do.full.models = F,
  metric.eval = evaluation_list,
  var.import = 10,
  nb.cpu = 24,
  seed.val = 123
)
modeval_for_evaluation
```

**Other outputs**
- The error message regarding MAXENT: `*** Error in MAXENT, more info available in  ./Models/keteleeria/models/1708967324/keteleeria_allData_RUN4_MAXENT_outputs/maxent.stderr`
- Contents of `maxent.stderr` file:
```
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using 'localhost:17.0' as the value of the DISPLAY variable.
	at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:105)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at java.desktop/sun.awt.X11GraphicsEnvironment.initStatic(X11GraphicsEnvironment.java:64)
	at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:59)
	at java.desktop/sun.awt.PlatformGraphicsInfo.createGE(PlatformGraphicsInfo.java:37)
	at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:93)
	at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:84)
	at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:106)
	at java.desktop/sun.awt.X11.XToolkit.<clinit>(XToolkit.java:225)
	at java.desktop/sun.awt.PlatformGraphicsInfo.createToolkit(PlatformGraphicsInfo.java:41)
	at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:595)
	at java.desktop/sun.swing.SwingUtilities2.getSystemMnemonicKeyMask(SwingUtilities2.java:2198)
	at java.desktop/javax.swing.plaf.basic.BasicLookAndFeel.initComponentDefaults(BasicLookAndFeel.java:1108)
	at java.desktop/javax.swing.plaf.metal.MetalLookAndFeel.initComponentDefaults(MetalLookAndFeel.java:444)
	at java.desktop/javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(BasicLookAndFeel.java:161)
	at java.desktop/javax.swing.plaf.metal.MetalLookAndFeel.getDefaults(MetalLookAndFeel.java:1564)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:591)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:633)
	at java.desktop/javax.swing.UIManager.initializeDefaultLAF(UIManager.java:1408)
	at java.desktop/javax.swing.UIManager.initialize(UIManager.java:1521)
	at java.desktop/javax.swing.UIManager.maybeInitialize(UIManager.java:1487)
	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1060)
	at java.desktop/javax.swing.JPanel.updateUI(JPanel.java:129)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:89)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:112)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:120)
	at ptolemy.plot.PlotBox.<init>(PlotBox.java:245)
	at ptolemy.plot.Plot.<init>(Plot.java:214)
	at ptolemy.plot.MyPlot.<init>(MyPlot.java:22)
	at density.Runner.initPlots(Runner.java:2389)
	at density.Runner.writeCumulativeIndex(Runner.java:1855)
	at density.Runner.start(Runner.java:493)
	at density.MaxEnt.main(MaxEnt.java:59)
```
- The attachment ( [R.txt](https://github.com/biomodhub/biomod2/files/14414749/R.txt) ) contains the conda configuration file for the current R environment, and it has been checked that `xorg-libx11` and other relevant packages are installed. 

**Environment Information**
``` 
R version 4.3.2 (2023-10-31)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Ubuntu 22.04 LTS

Matrix products: default
BLAS/LAPACK: /public4/group_wxk/home/wuxk/apps/envs/R/lib/libopenblasp-r0.3.26.so;  LAPACK version 3.12.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

time zone: Asia/Shanghai
tzcode source: system (glibc)

attached base packages:
[1] splines   stats     graphics  grDevices utils     datasets  methods
[8] base

other attached packages:
 [1] ggplot2_3.4.4        dplyr_1.1.4          terra_1.7-71
 [4] xgboost_1.7.7.1      randomForest_4.7-1.1 maxnet_0.1.4
 [7] earth_5.3.2          plotmo_3.6.2         TeachingDemos_2.13
[10] plotrix_3.8-4        Formula_1.2-5        gbm_2.1.9
[13] mgcv_1.9-1           nlme_3.1-164         gam_1.22-3
[16] foreach_1.5.2        mda_0.5-4            class_7.3-22
[19] rpart_4.1.23         nnet_7.3-19          biomod2_4.2-5

loaded via a namespace (and not attached):
 [1] utf8_1.2.4             generics_0.1.3         stringi_1.8.3
 [4] lattice_0.22-5         magrittr_2.0.3         pROC_1.18.5
 [7] grid_4.3.2             iterators_1.0.14       jsonlite_1.8.8
[10] plyr_1.8.9             Matrix_1.6-5           reshape_0.8.9
[13] survival_3.5-8         fansi_1.0.6            scales_1.3.0
[16] codetools_0.2-19       PresenceAbsence_1.1.11 abind_1.4-5
[19] cli_3.6.2              rlang_1.1.3            munsell_0.5.0
[22] withr_3.0.0            tools_4.3.2            reshape2_1.4.4
[25] colorspace_2.1-0       vctrs_0.6.5            R6_2.5.1
[28] lifecycle_1.0.4        stringr_1.5.1          pkgconfig_2.0.3
[31] pillar_1.9.0           gtable_0.3.4           data.table_1.15.0
[34] glue_1.7.0             Rcpp_1.0.12            tibble_3.2.1
[37] tidyselect_1.2.0       compiler_4.3.2         sp_2.1-3
```

**Comment by HeleneBlt** [comment]
Hi there, 
The error doesn't come from Biomod2 but probably from the setting of java. You can find some solutions [here](https://github.com/microsoft/WSL/issues/7006) or [here](https://stackoverflow.com/questions/10165761/java-cant-connect-to-x11-window-server-using-localhost10-0-as-the-value-of-t). It seems to be a common issue, you must find different solutions, but trying `unset DISPLAY` seems a good start.

Hope you'll find the solution soon,
Hélène

**Comment by WeiyeHuang** [comment]
Hi Hélène,

Thank you very much for your quick response and the suggested solution.

I followed your advice and added the `unset DISPLAY` command to my SLURM batch script, which successfully resolved the error I was facing.

I really appreciate your help in guiding me in the right direction.

Best regards,
Weiye
